### ISSUE TITLE
Passing a table deletes empty rows

### ISSUE THREAD

**Issue by lucasJedel** [numere-org/NumeRe#247]
For example, passing an empty table to a sub-window for the user to complete / fill out is not possible.

MWE:
currentTable:
<img width="383" alt="tab1" src="https://github.com/user-attachments/assets/8c029995-d662-45c9-a8eb-7055ea4e9a49">

**ROWS NOT EMPTY**
	rows{} = {1, 2}
	cols{} = {1, 2, 3}
	copy currentTable(rows{},cols{}) -target=editTable()
result editTable:
<img width="213" alt="tab3" src="https://github.com/user-attachments/assets/9832d410-3d40-46d3-86ce-8a007d09d40c">

**EMPTY ROWS**
	rows{} = {1, 2}
	cols{} = {2, 3}
	copy currentTable(rows{},cols{}) -target=editTable()
result editTable:
<img width="191" alt="tab2" src="https://github.com/user-attachments/assets/3e248202-a0d4-4259-b355-c192ad2644a9">

## Analysis
We'll use the planned `options` option as mentioned in #233

**Comment by numeredev** [comment]
@lucasJedel Can you provide a MWE to illustrate the problem?

**Comment by numeredev** [comment]
@lucasJedel Your problem is something else, isn't it? "Empty rows" are something virtual, which can but don't have to exist, i.e. each column may have a different amount of cells, but the table viewer just adds the empty cells at the end to make it appear as a table.

From what I understand, you actually want to provide a table to the user within a layout with a set of empty rows together with a defined set of column types. Is that the case?

**Comment by lucasJedel** [comment]
Yes basically.
Maybe I just expected to have 2 rows because of the line "rows{} = {1, 2}".

**Comment by numeredev** [comment]
Understood. So the requested change would be to have something like 
```
window ID -set value=TABLE() item=ITEM size={MINROWS,MINCOLS}
```
where `MINROWS` and `MINCOLS` indicate their respective minimal dimension, even if the table is in fact smaller? (Reminder: empty cells do not contribute to the table's size. They are purely virtual)
